### ISSUE TITLE
[Suggestion] - Autogenerated configs for mods

### ISSUE THREAD

**Issue by SSKirillSS** [yeelp/Distinct-Damage-Descriptions#10]
Rn this mod applies only one type of damage and resistance for every modded mob and weapon/tool. I suggest:
1. Apply more or less random values for every item, that extends default forge weapon/tool/armor class. Maybe make it based on damage/toughness/etc.
2. Apply same random values for every modded mob. Maybe make it based on health/resistance/bossbar/etc

**Comment by yeelp** [comment]
This seems plausible, I'd just need to find a way to iterate through such items/mobs. I had never thought about randomly generating config values. I would've assumed people would've preferred to tweak and enter each value manually. Same for the mobs.

**Comment by James103** [comment]
Will the defaults for modded mobs be pre-generated values that apply for all worlds and all playthroughs, or will you go the terrafirmacraft route of making the same modded mob type have different resistances depending on the world seed where the mob was spawned?

**Comment by yeelp** [comment]
Well, assuming I can even do the first one, which would be easier, there's no reason I can't have both options available

**Comment by SSKirillSS** [comment]
Hi. Any info about this?

**Comment by yeelp** [comment]
I was fiddling with CraftTweaker integration and decided to do that for 1.1.0 instead of the other features listed here. So this got pushed to 1.2.0. I'll be making a milestone where you can track development.

Or I could setup a Discord server for those wanting to track development more closely... not a bad idea actually.

**Comment by yeelp** [comment]
An interesting development... When mob capabilities are added, mob attributes (health, armor, etc.) haven't been set yet. I'm not aware of a work around currently, so I'll have to generate without health and armor information.
