### ISSUE TITLE
crash when use probeZS

### ISSUE THREAD

**Issue by LingJiuQiSan** [yeelp/Distinct-Damage-Descriptions#103]
[logs and crashreports](https://github.com/friendlyhj/ProbeZS/issues/10)
I found that in yeelp/distinctdamagedescriptions/integration/crafttweaker/capabilities/CTResistances.java calls ed a zenclass "mods.ddd.IDDDDamageType", but the correct is "mods.ddd.damagetypes.IDDDDamageType" in yeelp/distinctdamagedescriptions/integration/crafttweaker/types/ICTDDDDamageType.java this will cause game crash when use probeZS

**Comment by LingJiuQiSan** [comment]
https://github.com/friendlyhj/ProbeZS/issues/10

**Comment by LingJiuQiSan** [comment]
friendlyhj/ProbeZS#10

**Comment by LingJiuQiSan** [comment]
friendlyhj/ProbeZS#10

**Comment by yeelp** [comment]
That's pretty interesting. I'm surprised the CraftTweaker integration works at all even though this typo exists. Nice catch!

**Comment by yeelp** [comment]
Offending line in question:

https://github.com/yeelp/Distinct-Damage-Descriptions/blob/1432b5f2c907c472ecc2f9a1904d7c2c4b3e1dad/src/main/java/yeelp/distinctdamagedescriptions/integration/crafttweaker/capabilities/CTResistances.java#L22
