### ISSUE TITLE
Blocking an attacking that would normally set you on fire sets you on fire, though it shouldn't

### ISSUE THREAD

**Issue by yeelp** [yeelp/Distinct-Damage-Descriptions#105]
Vanilla behaviour is blocking an attacking from a zombie that is on fire should not set you on fire. In DDD, it does. Maybe add a toggle on if it should set you on fire or if the shield needs fire effectiveness OR if it should never set you on fire.

All of this assumes you can actually block the attack that would set you on fire.

**Comment by Xarmat-GitHub** [comment]
Thoughts:
- If the enemy is "burning" and attacks the player with any type of damage, then the player get burned as usual (vanilla behavior) 
- if the player can block the attack 100%, the fire can not be spread to the player 
- if the player blocks only 50% if the damage then: 
- A: it is a block, so the player will not burn (vanilla behavior)
- B: the player will be set on fire but only 50% of the duration 
- C: player get damaged, so he will burn allways 

Note: I recommend to go the way of the least risk for mod conflicts. And if possible, go the vanilla way (player's expectations on a designers perspective would be fulfilled, no wired behavior that must be learned a new).

**Comment by yeelp** [comment]
Done
