### ISSUE TITLE
[Suggestion] Armor Invulnerabilities

### ISSUE THREAD

**Issue by ShadeAware** [yeelp/Distinct-Damage-Descriptions#106]
Currently in my testing, no matter how high the damage resistance on a piece of armor is, you will always take at least ONE point of damage from an incoming source. For example, 1000% fire resistance on a piece of armor nevertheless necessitates you take one fire damage if you're standing in a fire block.

I think it would be nice if, above a certain threshold, the armor made you **immune** to that type of damage - or, failing that, the ability to define armor immunities like you can mobs would be swell.

**Comment by Xarmat-GitHub** [comment]
It would be an option to give armor immunity configuration when worn. The next thing would be configuration for armor set's (4 pieces) etc.

There are also other mods that allow potion effects when wearing a set of items. 

I also have created some craft tweaker scripts that allow to alter player DDD resistance when wearing armor or holding an item. So your request can already be made with craft tweaker at the moment.

I fear that the config get to big and updates and upkeep can take more time. Not sure if it would be worth it. Only Yeelp will know. ;)

**Comment by yeelp** [comment]
Yes, this can be accomplished with CraftTweaker scripts. Also since DDD is distributing armor points with armor distributions and armor points themselves have diminishing returns the more you have, this may be intended behaviour. I'll look into the minimum one damage situation though, as that might be an issue.

**Comment by yeelp** [comment]
This has been resolved in the latest release.
