### ISSUE TITLE
[Question] - EnderSkills compatibility

### ISSUE THREAD

**Issue by SSKirillSS** [yeelp/Distinct-Damage-Descriptions#11]
Can I somehow create separate damage type and apply it to every ES skill?

Mod link: https://www.curseforge.com/minecraft/mc-mods/ender-skills

P.S. Does this mod have Discord channel?

**Comment by yeelp** [comment]
So, ES looks like it uses it's own damage sources which means if you know they damage string it uses to internally recognize the different damage sources, then you can use that to define separate damage types via JSON. If ES uses potion effects to handle everything, then it won't be possible, as this mod doesn't differentiate potion effects for damage types.

From what I've seen in thir GitHub, it *should* be possible. If you enable debug mode in DDD and attack a mob with an ES skill, you can see the damage source string in the console, which may help (The debug mode doesn't really present information in a nice coherent way, so you'll have to try and dissect the information you need, was only intended for development purposes)

Currently this mod has no Discord channel. Never thought of making one actually...
