### ISSUE TITLE
The damagetype of tconstruct's tool didn't change when I change it's top parts

### ISSUE THREAD

**Issue by xjyjack** [yeelp/Distinct-Damage-Descriptions#110]
For example, when i made a stone frypan it's damagetype is 100% bludgeoning.But when i change the pan_head into a firewood one, it's damage is still bludgeoning but it should be fire.

**Comment by yeelp** [comment]
I assume you found a fix or realized what was going on but I was unable to replicate exactly what you've described. Using the default values, swapping a stone frypan head for a firewood one results in a 20% bludgeoning and 80% fire distribution

**Comment by xjyjack** [comment]
> I assume you found a fix or realized what was going on but I was unable to replicate exactly what you've described. Using the default values, swapping a stone frypan head for a firewood one results in a 20% bludgeoning and 80% fire distribution

sorry for not replying for a long time，I consumed a lot of time to test what's the excat promblem.
The problem is, for example, under default config, if I build a iron broadsword from tconstruct, its damage distribution is slashing 100%, and I change its head part into firewood ,its damagetype become fire 100%. But when I change its head part back into iron, its damage distribution should become slashing 100%, but the distribution won't turn from fire back to slashing immediately, sometimes the broadsword would keep making fire 100% whichever material I put as the head part. I only put ddd,mantle and tconstruct in my modpack
![Uploading 2024-10-09_08.57.34.png…]()

**Comment by xjyjack** [comment]
[
![2024-10-09_08 57 34](https://github.com/user-attachments/assets/34d416d7-f07c-4f61-b5e2-51dc72128eaf)
](url)

**Comment by yeelp** [comment]
From all my testing and tweaks I have been unable to recreate this. Check on the latest release (1.7)

**Comment by xjyjack** [comment]
> From all my testing and tweaks I have been unable to recreate this. Check on the latest release (1.7). Please reopen if you get the problem in the latest release

I tried 1.7 version, and if the modlist still only contain ddd,mantle and tconstruct, the damage distribution work properly.But once I put a tinker's addon( I tried 
 plustic and tinkers'reforged) and I enter an existing world, 
after a tool's head part was changed into firewood, it's damagedistribution is fixed to fire100% and won't change no matter what its head part is changed into any material.
<img width="213" alt="屏幕截图 2024-11-11 200434" src="https://github.com/user-attachments/assets/d84236dc-be5e-478b-a295-aafd61d3f076">
![2024-11-11_20 10 08](https://github.com/user-attachments/assets/be5f4e51-7edd-4207-a5c0-6146c6bf0c2e)
![2024-11-11_20 10 20](https://github.com/user-attachments/assets/9e8967b1-f4f3-4da2-b8eb-845bd963d8ea)
