### ISSUE TITLE
check this 

### ISSUE THREAD

**Issue by Arch23-tech** [yeelp/Distinct-Damage-Descriptions#111]
I hope this video will be motivation for Mr. yeelp to update the mod to 120.1 

https://youtu.be/dTd0zzRVQTQ?si=XoTWkLg7ImDLI9C_

**Comment by yeelp** [comment]
I appreciate your enthusiasm!

I've actually been decently hard at work adding a couple nice quality of life features to DDD for its inclusion in RLCraft specifically!

I intend to see where the mod is at after its 1.7 release. There may be a couple of other issues I'd like to complete before handling a 1.20+ rewrite of the code. The mod would likely have to be rewritten which would take a lot of time. Definitely something I'd like to do though
