### ISSUE TITLE
crash cause a incopatibility with wesser boys overlays mod.

### ISSUE THREAD

**Issue by xelotex** [yeelp/Distinct-Damage-Descriptions#13]
[crash-2020-08-24_12.23.02-client.txt](https://github.com/yeelp/Distinct-Damage-Descriptions/files/5119643/crash-2020-08-24_12.23.02-client.txt)

**Comment by yeelp** [comment]
(Sorry, I've been dealing with a lot lately, modding wasn't at the forefront of my mind)

The ResourceLocation for the shot arrow entity doesn't exist which causes the crash - which doesn't make much sense. I'll add a check for that, pop up a warning message, and we can go from there.

**Comment by yeelp** [comment]
commit 8e13ad07e21782c2fdcc41513776b85e354b01d2 should fix this for now. If new problems arise, open another issue.
