### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by HuangAdam** [yeelp/Distinct-Damage-Descriptions#15]
Server: CatServer-237b0d4-universal.jar

Crash: 
[crash-2020-09-04_23.25.52-server.txt](https://github.com/yeelp/Distinct-Damage-Descriptions/files/5176095/crash-2020-09-04_23.25.52-server.txt)

**Comment by James103** [comment]
Are you able to reproduce this crash?

**Comment by HuangAdam** [comment]
Yeah
Do you need the log?

**Comment by HuangAdam** [comment]
[latest.log](https://github.com/yeelp/Distinct-Damage-Descriptions/files/5176146/latest.log)

**Comment by yeelp** [comment]
(Had a lot of stuff to deal with lately, wasn't able to sit down and answer these right away)
I probably need to move the particle spawning into a separate handler that's registered client side only, if I had to guess.

I'll try this and see if I can get this tested on a server to verify it works. I assume this crash happens on server startup, before anyone can even join the server?

Also thanks @James103 for helping out here.

**Comment by HuangAdam** [comment]
Yeah
I can't open server if I install the mod.

**Comment by yeelp** [comment]
Well I definitely messed something up here pretty badly then. Will try to fix ASAP.
