### ISSUE TITLE
[BUG] The Twilight Forest - Hydra Mob

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#16]
**Infos:**
MC: 1.12.2
Forge: 14.23.5.2854

**Discription:**
While "The Twilight Forest - Mod" installed, come near a Hydra Cave (Structure in TW Forest, spawns a Boss Mob from a spawner) the game crashes.
_Hydra Cave Mob:_ https://ftb.gamepedia.com/Hydra

**Reproduce:**
- Teleport to DIM 7
- Search for a Hydra cave and come near
- When Mob try to spawn -> Crash

**Log:**
Latest Log: https://pastebin.com/mzbnkc9L
Crash Report (Vanilla Fix): https://pastebin.com/qc1Zv7tL

**Thought's:**
- Maybe the Hydra starts an indirect damage mechanic
-- So it is the same Bug as "[BUG] Splash Potion on GoG Mobs #14"

**Note:**
- The crash happens instantly, I was not able to see the mob

**Comment by James103** [comment]
I can't view the picture, can you try uploading it directly to GitHub?

**Comment by yeelp** [comment]
(Thanks for your patience, been busy)
Huh... Potentially related to #13 I think. Either way, adding a simple check ought to fix the problem at least.

**Comment by Xarmat-GitHub** [comment]
Picture Update, when needed:
https://ftb.gamepedia.com/Hydra

**Comment by yeelp** [comment]
I know Twilight Forest's Hydra is made of multiple parts. Like the head are separate entities from the body. That could be what's causing the problem, as TF probably handles resource location for multi part mobs in a unique way that differs from my approach of looking them up.

**Comment by yeelp** [comment]
Commit 8e13ad07e21782c2fdcc41513776b85e354b01d2 should fix this.
