### ISSUE TITLE
Crash On Server Side of SP

### ISSUE THREAD

**Issue by mmmilord** [yeelp/Distinct-Damage-Descriptions#18]
https://gist.github.com/mmmilord/58d8f7772b79d2bba4e12b01ce60759d

**Comment by James103** [comment]
Probably a duplicate of #6 and #14

**Comment by yeelp** [comment]
Almost certainly a duplicate

**Comment by yeelp** [comment]
commit 8e13ad07e21782c2fdcc41513776b85e354b01d2 should fix this.
