### ISSUE TITLE
[Suggestion] [HUD] - Damage Symbols

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#19]
### Readability / HUD Enhancement - Damage Symbols
- Pictures - not Text
-- Readability enhancement 
-- Use Symbols to show damage Types
--- no need for large text boxes
-- Lore: Player can interpret pictures faster then text

- Functionality
-- The three base Symbols are shown on all damage Items

- Config
-- max Symbols in a row (more then 3, makes the symbols smaller; the space on the Item will be divided by this value - default 3)
-- shift options:
--- hold shift to show additional information = true
--- show symbols any time = true (when false, player must use shift)
--- show text when shift is uses = true (at default, the player can see the symbols - but with shift he can read the test too)
--- Mechanic: Replace symbols with text when "show symbols any time" is enabled and the player press shift (no double information, symbols get overwritten)

- Extended
-- Player can set custom damage symbols and relate them to the custom damage type
-- Show Symbols when "max Symbols" are not full (weapon is 100% piercing, so only one slot is used, 2 more are free to use for custom damage symbols [Nice Effect: When "max Symbols" set to 5, then there is enough space for custom damage types])

![Damage Symbols](https://user-images.githubusercontent.com/69967920/93737059-6beb8800-fbe2-11ea-9554-9bf93bfe49be.jpg)

_Resources Picture:_ https://www.reddit.com/r/dndnext/comments/53tbuz/dd_5e_hit_effects_12_now_with_force_damage/

Thought: You are the boss, but better fix all bugs before feature creep 😉, tanks for the hard work 👍

**Comment by yeelp** [comment]
The pictures are cool idea. I'd like to get some that had a 'Minecraft' feel to them, so I'll either make them myself or ask someone. Currently, there's no tooltips to show what custom damage types a weapon inflicts, but some fiddling around might work.

(For reference for me later) I'm thinking something like:
Slashing: A sword slash. Picture the sweep attack from regular swords and make a small icon for that. Kinda like the icon for the Swing Through Grass mod on Curse Forge.
Piercing: A Spear thrust, which should be pretty intuitive.
Bludgeoning a thwack with some sort of club

For a reference size, I'm thinking about as large as standard HUD elements for Minecraft health/hunger (Which is 9x9 I think?). Then, the size fits nicely alongside other tooltip elements from other mods (Quark, AppleSkin, etc.) which will really help them blend in nicely. This may not work though, as the resolution of icons of that size may not led itself to much detail, which could make the pictures hard to interpret. The other size alternative is to go up to the next size, which I think is 18x18. Then, they'd match the size of Thaumcraft aspects (I ***think***),

Custom images are probably possible, and hopefully I don't have to rework the entire config directory system for that (probably not).
