### ISSUE TITLE
Update CraftTweaker page in wiki

### ISSUE THREAD

**Issue by yeelp** [yeelp/Distinct-Damage-Descriptions#21]
Getting some additional examples using CraftTweaker scripts would be nice.

Mainly need to reorganize the page to make sense and flow, make the documentation proper, concise and complete.

**Comment by evilchin** [comment]
Is there anyway that you could update the wiki with a few robust crafttweaker scripts that accomplish certain goals? Example off the top of my mind would be like defining creature groups, damage distributions, etc. Sorry for necro'ing a stale tracker. Just wanted to bring some attention to this in a productive way.

**Comment by yeelp** [comment]
Much appreciated! I've been pretty busy and have been unable to finish parts of the wiki, including ZenScript examples.

Don't worry about the necro, this is an important thing to highlight, and the suggestions for example scripts is actually much appreciated!

**Comment by evilchin** [comment]
Yea so some questions I had (or examples I was looking for) was like some scripts that have the capability of the config file, but I can use ZenScript to define them. I tried using the wiki to make a function that defines mob damage and resistances and I just could not get any of the methods to work or function correctly. Although admittedly this could be user error, so I'm not gonna rule that out completely.

Some great ideas for example scripts would be like a function that define mob resistances/damage, a script that define weapon damage distributions, and a script that can define creature types/groups. The first couple ideas I had might not be possible, but according to the wiki that last example should be somehow (I just could not get it to work).

Hopefully this helps, and let me know if you need any more input. Greatly appreciate the work towards this!

**Comment by yeelp** [comment]
[This page](https://github.com/yeelp/Distinct-Damage-Descriptions/wiki/DDD-ZenScript-Examples), created just now, includes two comprehensive examples so far, though the article itself is a little on the technical side. The creation of the second example during my live stream alerted me that creature types were broken and didn't work. That's been fixed in the 1.6.1 release which is being posted to all the usual places now.

I don't think these examples alone are enough to call this issue "done", but I would appreciate the feedback.

**Comment by evilchin** [comment]
These examples are pretty great in my opinion. They both use a ton of different functions which helps show how to use them. And they are in-depth enough to where I can use them as baselines to reverse engineer some things. Scripts like these really do help out when it comes to figuring out how to apply the mod via crafttweaker. Sorry I can't provide anymore examples or suggestions. Thanks for the help!

**Comment by yeelp** [comment]
The wiki now has four examples, which should be a pretty good reference to some of the things that can be covered.
