### ISSUE TITLE
[ Suggestion ] I make just a little improvement of textures:

### ISSUE THREAD

**Issue by ZettaSword** [yeelp/Distinct-Damage-Descriptions#25]
And here they are
![2020-10-06_10 35 35](https://user-images.githubusercontent.com/38763491/95173602-8cf6d000-07c1-11eb-9cf4-c8b6a4639852.png)
![2020-10-06_10 36 07](https://user-images.githubusercontent.com/38763491/95173603-8d8f6680-07c1-11eb-8845-5ad19c416357.png)

![2020-10-06_10 36 20](https://user-images.githubusercontent.com/38763491/95173585-8a947600-07c1-11eb-9912-dca402c870b8.png)
![2020-10-06_10 36 23](https://user-images.githubusercontent.com/38763491/95173594-8c5e3980-07c1-11eb-98a7-06a96ee82ff6.png)

You can use them, if you want :D 
This is just a little improvement, but i think textures now looks better

[DistinctDamageDescriptionTextures.zip](https://github.com/yeelp/Distinct-Damage-Descriptions/files/5332143/DistinctDamageDescriptionTextures.zip)

**Comment by yeelp** [comment]
These look way better. I'd love to use them. I'll include them in the next update.

I'll close this issue when they get added.
