### ISSUE TITLE
Currently missing wiki documentation

### ISSUE THREAD

**Issue by James103** [yeelp/Distinct-Damage-Descriptions#3]
I see that you currently do not have any sort of wiki set up for Distinct-Damage-Descriptions, with the only documentation available being inline with the code. Do you have any reason behind waiting so long before creating any documentation (such as waiting until first release)?

**Comment by yeelp** [comment]
I do intend on having a wiki, as that will help outline JSON config files etc. Just haven't gotten around to working on this project much in the past week or so (Which I'd like to reassure that it doesn't mean this project is dead, just been spending time on other things, and still in some discussions with people I'm collaborating with). Getting a wiki together before first release (or at least some of it) is probably a good idea, so thanks for the reminder!
