### ISSUE TITLE
[Suggestion] Potion Effects

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#30]
### Create Potion Effects for Resistant Types
Talked about that in "[Thoughts] Lets talk a bit #28".

**Description:**
Create Potion Effects that reduce or raise current defence of the target resistant types.

**Implementation:**
- As Potions: Throw able at targets / drinkable by player - change given Value by X
- As Enchantment on Weapons: Enchanting them so they decrease Effect of a given Type with by X% (or after each attack until an max value)
- On Armor to inflict this effect on the attacker
- On Shields to inflict this effect on the attacker

**Auto Creation Effects:**
- Every Custom Effect added in the config, will generate automatically an potion effect for this custom damage

**Comment by yeelp** [comment]
I'm thinking it's far more reasonable to have a potion effect that increases resistances across the board by say, 10% per level. You can also reverse this and decreases resistances by 10% per level. Dynamically creating potions on the fly sounds like a huge pain as you now need to create your own brewing recipes on the fly too. If you don't then you need to make sure CraftTweaker would be able to create these recipes on the fly instead, so I may stick with something a little more static.

Besides, an 'across the board' buff seems more usable and less niche.
