### ISSUE TITLE
[Suggestion] Bauble Integration

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#31]
### Create a Mod on DDD that allow Bauble integration

Talked about in "[Thoughts] Lets talk a bit #28".

**Functionality:**
- Additional Rings, Amulets that increase resistance of the player [Give 90% resistance against void damage]
- Rings, Amulets that increase damage inflicted by the player [All "Holy" attacks are increased by 50%]
- Rings, Amulets that adds custom damage to an attack [**Smite**: Adds 20% Holy Damage to your attack]

**Realisation:**
- Creating a Mod that can be added separate

**Quote from _Yeelp_**
> Bauble integration could allow a player to gain additional resistance to a damage type of their choice, or imbue their attacks with a custom damage type of choice. Although I'd have to make baubles for that probably. Chances are, I'll write a small addon mod that adds DDD based baubles. The code base will probably be in DDD itself but the addon mod will have the baubles and additional features related to Bauble integration (think how Quark Oddities is done).

**Comment by yeelp** [comment]
To expand on the quote:

There'd be two baubles, one for offense, one for defense. The offensive one would allow you to set a custom damage type for all your weapons. You could maybe pay a cost (in some form) to change it to something else.

The defensive one would work similarly, you pick a damage type and gain a resistance to it. You could then pay a cost to change that resistance to something else.

These sound pretty strong on their own, as it allows you to avoid the whole "bring the right weapon/armor to the fight" idea. Maybe you won't be able to change the damage type, you just set it once and that's that. Needs more thought.

**Comment by yeelp** [comment]
Whether I want to do some specific compat or not, I'm going to push the issue back for a later project and not for 1.4, should I choose to add anything for it

**Comment by yeelp** [comment]
Bauble compatibility and integration has been added in 1.7
