### ISSUE TITLE
[Suggestion] [HUD] - Hwyla Integration

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#32]
### DDD Information on the Hwyla Mob Interface
**Future Talking:** Creating an AddOn for Hwyla so that players targeting the enemy would see there resistant values, attack values and costume values.

**This Ticket depends on the implementation of:**
- "[Suggestion] [HUD] - Damage Symbols #19"

**Goal:**
- Give the player a basic knowledge to chose the right weapon when looking at a mob
-- Expert Players will dig deeper into the mechanics and will know exactly witch weapon and custom damage will be more effective

**Comment by yeelp** [comment]
There might be too much info to display with custom resistances, so I may limit it to physical resistances only for the time being.

**Comment by yeelp** [comment]
closed by #56
