### ISSUE TITLE
[Suggestion] Feedback Positions in Fights

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#33]
### Feedback while playing with DDD

**Goal:** 
The player must understand the situation he is in after the second blow. 
How hard will this fight be and should he better retreat and change his weapon / armor quickly.

**Possible things the player want/need to know while FIGHTING:**
1. Does my weapon perform well?
2. Did I blocked this damage with my shield?
3. How much damaged my armor block?

**After the fight:**
1. How much damage I did with each blow?
2. Was there damage my shield did not blocked?
3. How effective was my armor, how much reduction was there?
4. What Resistance the enemy had?
5. How strong was the armor he wear?
6. Which type of damage he did?
_This is worth an own ticket, I don't clarify it here_

**Instant Possible Feedback Options:**
- Visual: HUD Element | Symbols on Mobs 
- Sounds: Play Sound when criteria is meet
- Text; "You did less then 20% weapon damage"

**Notes:**
- _The Player is first of all interested on the total performance in the fight, when one kind of damage get 100% blocked and the weapon does 20% less damage, then its fine for the player - only the total damage is interesting while fighting. That means that the player is not in need to know that one damage type get blocked. This is only interesting after the fight in a "Post Mortem" reflection_

**Possible Instant Feedback Positions AND system reactions:**
- ALL Damage get blocked by Enemy Shield 100% 
-- _(Vanilla Sound of TOTAL BLOCK)_
- The Main Damage Type (most % value on weapon) get negated by Enemy Entity Resistance 100% 
-- _(DDD Sound that the main damage type of the weapon don't perform at all)_
- The total Damage received by the entity is less then:
-- <70% | <50% | <30% of the players attack
-- _(After a player attack, that damage get through the calculation. At the end, DDD plays a hit sound how well or bad the weapon perform. When more then 70% of the total damage landed on the entity, all is well and it will not play any sound. When less then 50% of total damage landed, then it will give a light sound feedback. When less 30%, it plays a "hard" sound and the player will be in alert and can react_
- Player Shield Blocked 100% of incoming damage 
-- _(Vanilla Sound of TOTAL BLOCK)_
- Player Shield Blocked less then <99,9% | <60% | <30% of incoming TOTAL damage
-- _(Look above "The total Damage received by the entity is less then:" - but with other sounds that refer to shield blocking)_
- Player Armor perform so bad, that less then <50% of the armor points are used while calculating
-- _(Like above)_
> Player get hurt by <30% | <60% | <100% of damage the enemy can possible deal
>_(Change the Hit sound from Vanilla when a player get hurt. 30% -> just a light sound, 60% the normal vanilla sound -> 100% some extra on top to alert the player)_
_Not interesting, because player get always 100% damage from mobs. And when he has nor armor its totally normal. When he has armor that perform bad, then the armor sound will be played, so no need for this._

**Extra Thoughts:**
- Armor stays armor, the player know when fighting that much of his damage don't get throw this diamond full plate. So for DDD its more interesting to give the player feedback on the other parts and ignoring the damage blocked by the armor -> At least for the instant feedback.
-- _(So the Feedback ignores the armor reduction and play a sound as if the entity don't wear any armor.)_
-- _(Most time armor has only 4 options: No armor, cloth/MagicCloth, light/Lether, medium/chains, plate/fullPlate -> the player will learn fast which weapon type is good against the enemy armor, an extra feedback on this can overwhelm him)_

**Content List for Sounds and Graphics:**
- Player Weapon performance is not the best, or bad - informative
- Player Main Damage Type is useless totally - warning
- Player Armor performance is bad - warning
- Player Shield Performance is not the best, or bad - informative

**Comment by yeelp** [comment]
The biggest problem is there is only limited ways to communicate information to the player and I really, REALLY don't want to add a bestiary book type item as GUI's in Minecraft are a total pain and I don't have a lot of practice with it. Such a book item would be the easiest way to do things though. Kill an enemy, and you learn about it in the book (maybe you need to book in your offhand or hotbar or whatever, not worth considering right now). Such a book item would solve the problem; you know their resistances, and damage distribution. All you need to know is the armor and weapons they carry. Assuming you don't have JEI (which just makes this a simple lookup) you need to craft the item first to know the distributions it carries.

A cool concept for a book but again, I have little experience with GUI's and it's not an easy task.

In terms of mob resistances, the current sound system is "good enough" for determining if your attack is resisted or enhanced.

Mob damage on the other hand is a bit tricky. I could spawn coloured particles, where the colour of the particle is defined in the JSON but I don't want the player's screen to light up in a million colours particles whenever they take or deal custom damage.

**Comment by Xarmat-GitHub** [comment]
I know this is challenging. Feedback is a lot of try and error.
And set things right is quite a challenge. I hope you will get the right way to achieve things.

But this is kind of a process, so making something "light" and test it with your user base is a good start.
This Ticket has a lot of Brainstorm and putting Thoughts together, but it's totally not a guarantee that it will be "nice and round".

___

Maybe use the Armor GUI and spawn Particles on the Armor Bar when the player get hit.
Then you can use the same Particles from the Enemy's/Entities and the player can see which color there Armor Perform (100% Armor Value or less)

Problems:
Need a way to place them on the Screen, there are many Role-play Mods that replace the bar with something different.

Opportunity:
But the bottom Bar is one of the main Information Sources of the game. So placing there Particles that fly up 2-3 cm from the armor bar can help the player a bit.

___

"THE BOOK"
This is a pain, that I am sure. I wonder how Botania achieve the nice Ingame Wiki.
One thing I Thought of was: 
https://www.curseforge.com/minecraft/mc-mods/universalbestiary - Universal Bestiary (Book with Mob Description)
https://www.curseforge.com/minecraft/mc-mods/patchouli - Patchouli (Book Creation)

But that's a lot of content to write down and I don't know how good they can import Informations out of Configs (like import DDD values automatically). Also there is the point of adding Mooded Mobs.

But one more thing:
Maybe use Scroll List (ah dam again a GUI) on the Right Side of the screen.
It would be like the Chat and pups up when the player hit an entity.
There can be all basic informations of the mob and it scrolls up and disappear after 10 Seconds.
By pressing "Hotkey" the list will spawn again.
When opening the chat, the player can scroll through it, to look over the last mobs.

Problem:
Custom Damage Types

____

Lots of options, not sure what is worth to go for exactly.

____
In my Modpack, I want to introduce the different damage types over several Game Phases by adding for each stage a new Damage Type that will be only Used in Special Places.

Examples:
- Player get Game Stage "Spear" (Piercing Damage)
- He get the Quest to go to the Marsh
- The Mobs there have low resistance on p damage
- Then the player learn where to use p damage

Same with Custom Damage:
- Find the way to make "Holy" Items (Holy Damage)
- Get the Quest to Kill Undead
- Get Attacked by Lich Mage (Magic Necrotic Damage)
- Get a hint to enchant his Armor also with holy damage

After several hours, the player gets involved into this System and know how it works.

**Comment by yeelp** [comment]
I'm closing this as the transparency already provided by DDD and especially with other mods like HWYLA is sufficient
