### ISSUE TITLE
[BUG] Icons in Tooltips

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#37]
I test the Icons and this is what I found:

**Note:**
- Config Values are unchanged
- Changed Elements:
-- B:"Show Damage Distribution Tooltip for all items"=false
-- B:"Use Damage Type Icons"=true

1. Icons Appear on Items with no damage settings
[http://prntscr.com/wl3vv4](http://prntscr.com/wl3vv4) ;[http://prntscr.com/wl3jsq](http://prntscr.com/wl3jsq)

2. Icons on Armor are Shifted
[http://prntscr.com/wl3l4k](http://prntscr.com/wl3l4k)

3. Spawn Eggs are also shifted

**Comment by yeelp** [comment]
Well with #38, which I something I plan to do, the misplacement of these icons would be essentially fixed.

I'll make sure to triple check this time around so it doesn't happen again.
