### ISSUE TITLE
[Suggestion] Icons Behavior - Item Tooltip

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#38]
1. In the Item Tool Tips, there is enough space to place all 3 Icons Side by Side
[http://prntscr.com/wl3o8n](http://prntscr.com/wl3o8n)

2. A Config Option to turn the visibility of the Icons / Text to "Permanent ON" would be great [Also disables the Text "Damage Destribution:"] - This would clean the Tooltips - [http://prntscr.com/wl3s6a](http://prntscr.com/wl3s6a)

**Comment by yeelp** [comment]
I had planned to place them all on the same line in the tooltip, but that required a bit of a rewrite to the way I do tooltips. Their current implementation required no rewrite (Basically don't add the damage type string, just use the icon), so I went with that to at least get them in. 

Your second point is a good idea, but such a feature should reasonably apply to armor values, projectile distributions and shield distributions as well. If a piece of armor has an armor distribution and a damage distribution, then it becomes hard to tell which is which if the text "Damage Distribution" and "Armor Effectiveness" aren't present. I may still want to keep those text in the tooltips for clarity. This of course also applies to shields (Maybe a spiked shield does piercing damage, so a damage distribution tooltip is needed). and projectiles (vanilla arrows do piercing damage when used as a weapon *and* when fired as a projectile). I also like the idea of keeping the text for when DDD is packed with a bunch of other mods that add stuff to tooltips (Like Quark, AppleSkin, etc), again, mainly for clarity.

**Comment by yeelp** [comment]
Given how #58 adds additional damage types, it makes more sense to display icons in a list as opposed to inline, as a list scales better for multiple categories (And having some threshold to change from inline to list is awkward, not to mention an inline display would be trickier to begin with), so I'm going to scrap that idea.

The second part is still good though (already done actually) :+1:
