### ISSUE TITLE
[Suggestion] Advanced Zen Script (Craft Tweaker) Integration

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#39]
Chat Copy: https://discord.com/channels/750481601107853373/750482330061373480/805110445744455710

## Setting DDD Damage Types with Zen Script
Example Script: <item:minecraft:diamond_pickaxe>.withTag(something).setWeights(s, b, p, ...)

**Enable Damage Type Changes by:**
- Unlocking a Game Stage (and all other ZenScript Mods that can handle this)

Unlock endless options to use DDD dynamically .

**Comment by yeelp** [comment]
This is likely handled somewhat by the new CT events and features.
