### ISSUE TITLE
Missing text for 5 translation strings

### ISSUE THREAD

**Issue by James103** [yeelp/Distinct-Damage-Descriptions#4]
As of Distinct Damage Descriptions 1.0.0-beta, the following translation strings are missing proper text:
* `distinctdamagedescriptions.general.damage.mobbasedmg`
* `distinctdamagedescriptions.general.damage.projectiledamagetypes`
* `distinctdamagedescriptions.general.damage.itembasedamage`
* `distinctdamagedescriptions.general.resistance.armorresist`
* `distinctdamagedescriptions.general.resistance.mobbaseresist`

(There may be more)

**Comment by yeelp** [comment]
So this isn't a huge deal for the patch I'm releasing now, so I won't include it.

Anyone else is welcome to open a PR with these translation strings added if they want.
