### ISSUE TITLE
[Visual] Mockup for Curseforge

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#40]
## Description
Creating one or more Mockup's to explain the functionality of DDD on CurseForge.

## How to do this?
I want to use [this graphic](https://prnt.sc/w3icr0) for the base discussion.
Feel free to say what you wish Yeelp. I will try to get into it and make it like you want it.

**Some Elements to think of:**
- Graphics: Better use DDD Graphics in the Mockup, my own graphics are from different kind of mods (+only use Vanilla Items, they will not cause any licence problems)
- Communication on GitHub is kind of heavy, because the Discord Chat is silent at the moment, I want to discuss elements in the "ddd-development-discustion"
- Make things simple - Maybe one normal Mockup without Custom Damage can be created for the Top of the Curse Page

**Comment by Xarmat-GitHub** [comment]
**Next Steps:**
- Import and Replace Textures / graphics from the mod
-- Shield Symbol
-- S,P,B Icons
- Create / Find 2 Icons for costume damage
- Create two versions -> 
- - one with %
- - one with numbers


**Options:**
- Create a Gift to switch between Number and % Values every 3 seconds

**Comment by Xarmat-GitHub** [comment]
Version 01: http://prntscr.com/yuom8t

**Comment by Xarmat-GitHub** [comment]
Next Steps:
- Brainstorm how the Mockup can wake more interest
- Import the shield Icons from GitHub and replace them

**Comment by Xarmat-GitHub** [comment]
Idea for more "Interest":
- Create a .GIF that shows the damage changes step by step
-- e.g.: Mob Damage + Weapon Damage - Shield Block - Armor Block - Natural Resistance
-- So having a Static Picture on top and a step by step GIF for the player to follow and understand the functionality and opportunities

**Comment by yeelp** [comment]
That sounds pretty cool, although I don't have the knowledge to make gifs.

A base mockup should be good to start, then go from there, although the mockup would now have to incorporate the new damage types

**Comment by Xarmat-GitHub** [comment]
I have some software to create GIFs. As soon I learn the new system / damage types, I will add them to the Mockup (when it dosn't overload).
I will try to make a nice GIF that explain the mod step by step.

**Comment by yeelp** [comment]
That would be wonderful!

**Comment by Xarmat-GitHub** [comment]
Idea:
- Make 6 GIFs with each 2 Situational use / explanation 
- 1. Weapon Damage Splitting (Sword = Slash | Pickaxe = Piercing)
- 2. Armor Effectivity (Iron Armor vs Piercing | Chain Mail vs Piercing)
- 3. Shield Block (Bludgeoning vs Vanilla Shield | Slashing vs Vanilla Shield)
- 4. Mob Costume Damage (Skeleton = Piercing | 
- 5. Mob Resistance (Skeleton vs Piercing | Skeleton vs Bludgeoning)
- 6. Custom Damage (Zombie = Necrotic | Blaze Shot = Fire)

Questions:
- Q1: Would it be "OK" to use Spartan Weapons to explain it? 🤔 
- Q2: Should I use the in Build Costume Damage Types? - At the moment the "Armor" don't work well enough to explain it well... (maybe "6. Custom Damage" is enough for now)
- Q3: Is other Stuff also needed? Like Projectiles, Falling Blocks, Drown Damage, etc...

Future:
- Explain Baubles Stuff (Antidote Amulet = 90% Poison Resist | Holy Amulet = Extra 50% more holy Damage)
- more...

**Comment by Xarmat-GitHub** [comment]
Feedback Needed:
- GIF Version 1: 
![DDD_1WeaponGIF](https://user-images.githubusercontent.com/69967920/111991923-20745100-8b15-11eb-8af1-6eb3addc5e5a.gif)
- What do you think? All other Categories will also switch like this. Its simple and it should explain the 3 physical damage types.
-- Give me your thoughts

**Comment by Xarmat-GitHub** [comment]
Shield GIF:
![DDD_3ShieldGIF](https://user-images.githubusercontent.com/69967920/119107654-b9452100-ba1f-11eb-8e5a-807846afbcdd.gif)

When something is not fine, or you want other values, then just say something. 😁

**Comment by Xarmat-GitHub** [comment]
NEW: [Google Drive Repository](https://drive.google.com/drive/folders/19VKzCkZ93q_YgurBsBdO8X3ZIxV1rB1w?usp=sharing)
I upload all the stuff that I am doing. This will allow you easier access. ^^

**Comment by Xarmat-GitHub** [comment]
@yeelp I think I will get soon some time to spend on the visual "upgrade" for the Curse site.
I thought to explain / create gifs for the custom damage types next.

Now my question: Is the current gif format, quality, layout ok? Do you have wishes or something that must/should be changed?
Let me know. 😉

**Comment by Xarmat-GitHub** [comment]
Custom Damage:
Explained with Fire Only
![DDD_4CustomGIF](https://user-images.githubusercontent.com/69967920/133072611-469252be-8452-4193-9ec5-6c00c8d1ccf3.gif)

**Comment by Xarmat-GitHub** [comment]
Mobs / Entities:
![DDD_5MobBGIF](https://user-images.githubusercontent.com/69967920/133081608-686c7336-e23c-40e2-bf2c-5e8d8beffd19.gif)
![DDD_5MobSGIF](https://user-images.githubusercontent.com/69967920/133081609-862b9a3a-ff59-42d9-8820-1a9c4e2f0718.gif)
![DDD_5MobZGIF](https://user-images.githubusercontent.com/69967920/133081616-bad12168-7472-45d9-be6d-90d291d598c7.gif)

There are more features (as I learned today) like bypass.
@yeelp Is there more that should be visualised somehow? Can you make me a list 🤔

**Comment by yeelp** [comment]
These gifs are super cool. Good work!

You can, if you want, visualize the enchantments, but they're relatively straightforward to wrap one's head around once they have a base foundation (provided through these gifs), so I wouldn't say it's necessary.

May I suggest showing mob immunities though? And maybe like, showing an example calculation of a weapon going through mob resistances, armor and immunities. I believe the specific calculation order is resistances/immunities (done together) then armor afterwards. Then the damage is summed up across all categories, and only then potion effects (like resistance) and natural armor are applied. So, something like a magma cube getting hit with a weapon that struck a resistance, weakness and immunity all in one. It'd be a great way to show how the entire calculation works, from distributing the damage, to reducing it in the various ways, summing it up, then applying potion effects and natural armor

You can also do a brief gif of adaptive resistance, basically indicating how a mob's resistance changes if they take damage. The default values for Silverfish showcase this quite well, being able to completely negate piercing damage when their adaptability kicks in. A "before and after" example, like "before adaptability, the silverfish takes this much piercing damage. Then it gets adaptability, and it takes no damage from piercing damage" You could fade between the before and after (kinda like how you did for the weapons/armor/shields), only changing the values that change as a result of the adaptability.

**Comment by Xarmat-GitHub** [comment]
Slay Strike Example:
![DDD_4SlyStrike](https://user-images.githubusercontent.com/69967920/135582751-e9ba0d50-8e15-4fea-ab01-1472d30ea88e.gif)

**Comment by Xarmat-GitHub** [comment]
Bruteforce Version
![DDD_5Bruteforce](https://user-images.githubusercontent.com/69967920/135586255-60bcdb3f-ad49-4d4f-9285-d8277143dce3.gif)
:

**Comment by Xarmat-GitHub** [comment]
Adaptability Version
![DDD_6Adaptability](https://user-images.githubusercontent.com/69967920/135588684-10a3332e-a2f8-4359-9451-364648abb1f1.gif)
:

**Comment by Xarmat-GitHub** [comment]
Full Mechanic Explanation:
![Full Mechanic Explanation](https://user-images.githubusercontent.com/69967920/135596054-c3709622-c48a-4795-813e-b64a6b819b50.png)

**Comment by Xarmat-GitHub** [comment]
Ok, I reach a Milestone. 
I need Feedback what you want to change on the GIFs / Mockups ➕ more mockups if needed 🍷

**Comment by yeelp** [comment]
Perfect! These are great! I don't think there's any more gifs that are needed that I can think of

**Comment by Xarmat-GitHub** [comment]
Nice, you can find all GIFs / Mockups in this Google Drive Folder: [Google Drive Repository](https://drive.google.com/drive/folders/19VKzCkZ93q_YgurBsBdO8X3ZIxV1rB1w?usp=sharing)
I put them in the "GIF" folder.

**Comment by yeelp** [comment]
A good majority of these have been uploaded to the Modrinth gallery and used in the Modrinth and CurseForge project descriptions. So I'm going to close this at long last.
