### ISSUE TITLE
[Tooltips] Have Spawn Eggs show mob Damage Distribution instead of item Damage Distribution

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#43]
**Spawn Egg [visual / informational bug]**
- Show False Tool Tip Information **"DAMAGE DISTRIBUTION"** only [Mob Resistances works fine]
- Should be: "minecraft:polar_bear;0.25;0;0.75"
- But is: "100% b"

- Note: All other Spawn Eggs have the same problem -> 100% B damage, other damage types are not shown
- Notes: 
-- The Console works fine, the damage is split by S,P,B like in the config - so its only a visual / informational bug
-- So Resistance works like they should
-- Damage calculation works (mobs with resistance take less damage - so the console informations are right)
-- B Immunity on slime works, it takes no B damage at all

**Comment by yeelp** [comment]
The damage distribution is for the spawn egg itself, not for the mob spawned. Yeah that's a little misleading, but that's technically correct behaviour. Probably better if it showed mob damage instead...

**Comment by Xarmat-GitHub** [comment]
Ohh then its a miss reading on my side... 😅 
Sorry for that.

But is there a way to see the Damage the Mob is causing on the spawn egg or somewhere else? 🤔
Maybe it can be put into the Resistance section of the mob egg.
