### ISSUE TITLE
[BUG] No Custom Damage Support

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#44]
Custom Damage don't seam to work.

Config: https://pastebin.com/qnSW6F5R
Folder Path: http://prntscr.com/z7f6gz
JSON Script: https://pastebin.com/nmwUuwfZ

**Tests:**
- Test with console
-- Attacking Spider with Stone Sword: 100% B Damage (0.5 s damage get ignored, so DDD ignores the entry totally)
--- **"Weapon Base Damage"** ignores entry
-- Spider Take 100% B Damage (no S damage from stone sword or any "holy" damage)
--- **"Mob Base Resistance/Weakness"** ignores entry

**Comment by yeelp** [comment]
This is odd... Everything works for me... I am working on a dev build... maybe I fixed it already?

However, I did forget to actually give mobs any custom immunities that are specified, so I'll fix that.

**Comment by yeelp** [comment]
If custom damage still isn't working for you in 1.2.1-beta, reopen this issue
