### ISSUE TITLE
[Bug] damageArmor is passed the wrong Map, no armor gets damaged for players.

### ISSUE THREAD

**Issue by yeelp** [yeelp/Distinct-Damage-Descriptions#45]
Apparently Armor doesn't take durability damage... Pretty sure it does, but check anyway.

**Comment by yeelp** [comment]
Oh nooo...

https://github.com/yeelp/Distinct-Damage-Descriptions/blob/ccdfc0d23a02d4f8027f5517c2c526e06dc14e10/src/main/java/yeelp/distinctdamagedescriptions/util/DDDCombatRules.java#L271

Look at this derp.
I pass the resistances in instead of the absorbed damage. Good for me. Players don't have resistance -> no armor damage.

**Comment by Xarmat-GitHub** [comment]
Oh, did not test armor yet. Wait for the Custom Damage Fix 😅 
Good that you find it before you update a fix. :)
