### ISSUE TITLE
Build in more damage types

### ISSUE THREAD

**Issue by yeelp** [yeelp/Distinct-Damage-Descriptions#46]
Build in the base damage types from D&D, which should make using elemental damage a little easier. I'll still support custom damage, but building in these just makes things a little easier. Like yes, lightning bolts would always do lightning damage if lightning damage were added, so just cut out the extra work and build it in. Would require a bit of a rework, but it might make things a little easier going forward.

For reference, the damage types are:

slashing
bludgeoning
piercing
acid
cold
fire
force
lightning
necrotic
poison
psychic
radiant
thunder (may rename to sonic damage, not sure)

most won't be used in vanilla. (Fire is obvious, lightning I mentioned, necrotic from wither, poison from poison effect (maybe cave spiders too), force could be from magic damage (maybe)). But adding them makes using them easier, plus I can add textures for them too

Thinking of using an enum or something for this...

**Comment by James103** [comment]
When you feed a Parrot with a Cookie, that currently deals `Float.MAX_VALUE` bludgeoning damage (the default damage type). I suggest that feeding a Parrot with a Cookie should deal `Float.MAX_VALUE` poison damage as that effectively/thematically poisons the parrot to death.

**Comment by yeelp** [comment]
Oooo fair point. Let me add that
