### ISSUE TITLE
Crash when using arrow spells from MK: Ultra and mobs and player dealing double the damage

### ISSUE THREAD

**Issue by viperc48** [yeelp/Distinct-Damage-Descriptions#47]
Game crashes when a mob is hit by an arrow spell from Mk Ultra. For some reason, mobs and players also deal double the damage that they're supposed to do.

Crash: 
[crash-2021-02-28_16.52.28-server.txt](https://github.com/yeelp/Distinct-Damage-Descriptions/files/6056471/crash-2021-02-28_16.52.28-server.txt)

Latest:
[latest.log](https://github.com/yeelp/Distinct-Damage-Descriptions/files/6056473/latest.log)

**Comment by yeelp** [comment]
The double damage thing I'm not too sure about... but the game crash is something I can fix. Does the double damage happen only with MK Ultra, or MK Ultra related spells, or does it happen with just DDD?

**Comment by yeelp** [comment]
While the issue may still be present in the current version, you're also using an outdated version (1.1.1-beta). Mind updating to the latest and checking again?

**Comment by viperc48** [comment]
The 2 issues still persist on the latest version and the double damage still happens with only DDD, and HWYLA and WailaHarvestability active.

[crash-2021-03-01_20.33.11-server.txt](https://github.com/yeelp/Distinct-Damage-Descriptions/files/6061703/crash-2021-03-01_20.33.11-server.txt)

**Comment by James103** [comment]
Have you tried disabling HWYLA and WailaHarvestability as well to see if the double damage still persists?

**Comment by viperc48** [comment]
Yeah everything is still doing double damage.

**Comment by viperc48** [comment]
Encountered another 2 crashes when attacking a CQR skeleton( carrying a shield) with a bow and with a diamond sword

[crash-2021-03-02_20.16.54-server.txt](https://github.com/yeelp/Distinct-Damage-Descriptions/files/6068552/crash-2021-03-02_20.16.54-server.txt)
[crash-2021-03-02_20.15.56-server.txt](https://github.com/yeelp/Distinct-Damage-Descriptions/files/6068554/crash-2021-03-02_20.15.56-server.txt)

**Comment by yeelp** [comment]
Completely unrelated to the other crash.

I didn't know non player mobs could use shields... Interesting...
