### ISSUE TITLE
[BUG] No Custom Damage Support II

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#48]
#44 related

Still I can not get it to work.
Here is some testing and my config / scripts:

Config: https://pastebin.com/syLejn4H
Custom Script: https://pastebin.com/bzgnezqA (in config/distinctdamagedescription/damageTypes/holy_damage_type.json
Note: I delete all comments, also the Version Number on top. Only the JSON Format stayed.

Testing Items / Mobs:
- Iron Sword (damage 50% holy)
- Polar Bear (attack 50% holy)
- Cow (resist 50% holy)
- Iron Chest Plate (50% armor value vs holy)
- Shield (50% block vs holy)

ToolTips:
None or only "bludgeoning"

Console Testing:
Only Bludgeoning, no holy damage

_____
- Maybe my setup is false, is ""dmgSource": "indirectMagic"," maybe wrong or something diffrent?
- does the "ddd_" prefix is needed?
- I dont know : D test a lot and dont have a hint for you : /

**Comment by yeelp** [comment]
"ddd_" prefix is needed. Can I have a copy of the log? I definitely feel like something isn't set up correctly

**Comment by yeelp** [comment]
Found the problem while working on #49

See this?
`[(ddd_holy,0.5)]`

You need a space. It needs to be:
`[(ddd_holy, 0.5)]`

Very silly, I know. I've fixed it in #49. The space is no longer required. My bad. 1.3 will take some time, so just add the space for now.

**Comment by Xarmat-GitHub** [comment]
On nice, thanks for the info. 👍
