### ISSUE TITLE
[BUG] Arrow can not use Costum Damage

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#51]
Config:
S:"Projectile Damage Type" <
            minecraft:arrow;0;0.5;0;[(ddd_holy, 0.5);minecraft:arrow,minecraft:tipped_arrow
         >

Behaviour:
- Arrow show 0% holy damage -> http://prntscr.com/10byzlr
- When try to fire it, it dont shoot anything and cancel the attack
-- Log: https://pastebin.com/EAMpfJzh -> (because the arrow damage is not "1" in total)

What I try:
- Test it without "space" (ddd_holy,0.5) -> reset to 100% B Damage

Thought's:
- I think DDD read the line with errors

**Comment by yeelp** [comment]
This might be fixed by the refactor in #49, but this is something I will double check.

**Comment by yeelp** [comment]
Checked on current development version, everything works as expected now :+1:
