### ISSUE TITLE
[suggestions] option for actual values and resistance reduction based on weaknesses

### ISSUE THREAD

**Issue by Biviho** [yeelp/Distinct-Damage-Descriptions#52]
hi, i wanted to make two suggestions:

the first one is about adding an option for showing actual value instead of percentage for weapon and armor to have a more direct way of comparing items.
Currently one have to actually calculate the percentage value of an item to know if that item is actually better in a specific stat.

the other is an option for a new mechanic: "adaptability weakness"
the idea is that if you attack an enemy with a weakness, with adaptability, using that weakness, the amount of adaptability he get is reduced proportionally to the weakness amount and element amount (there could be a better formula).

for example: let's say the adaptability weakness is based on middle value between weakness and the element amount.
using the spider example: 
-the spider have 25% Bludgeoning weakness, 25% Piercing Resistance and 0% Slashing Resistance.
-he get hit with a wooden pickaxe with 50% Bludgeoning and 50% piercing.
-his adaptability weakness value is the middle between the bludgeoning weakness and element, so 25 + 50 / 2 =37,5
-the spider have an adaptability of 25, so it will be reduced by 37,5% = 15,625
-the final resistance value will be 9,375 bludgeoning weakness, 40.625 piercing resistance and 40,625 slashing resistance.

as i said there could be a better formula, something like a proportional value of weakness and the element amount together, or using the element damage, the middle value was only an example

This way it would be possible to create some interesting design for modpack developer, like, for example, creating dimension specific custom element and making enemy of that dimension weak toward that specific dimension element to incentivize players to use specific tools in specific dimensions while keeping the depth of a damage type based system

**Comment by Biviho** [comment]
for the first point yeah, that's why i didn't take into consideration mobs and projectiles, but just weapons and armor, as they already have a reference value.

for the second point, sorry, i'm not a native english speaker, glad you find it reasonable, i admit it's something i actually need in my pack, so it's some sort of selfish suggestion let's say...
i actually should be able to make the dimension based damage type without this feature, but it would be a shame to have to sacrifice the classic damage type system

**Comment by Xarmat-GitHub** [comment]
That is a good idea to show the damage / armor values as numbers. 👍 
Experiment so long with this and didn't realize it in game. 😂
