### ISSUE TITLE
[1.3-PRE-1] requires hwyla to be installed in order to prevent a crash

### ISSUE THREAD

**Issue by Nathan22211** [yeelp/Distinct-Damage-Descriptions#59]
here's the crash when it's not installed https://gist.github.com/Nathan22211/62b5dfe85ba8eabe0fdebe4b6520d6cf

**Comment by yeelp** [comment]
I have an idea that can likely fix this, although I'm still unsure why it happens to begin with. Something about annotating the class makes it not exist when running without Hwyla

**Comment by Xarmat-GitHub** [comment]
Add my crash report too:
[crash-2021-06-24_18.37.16-client.txt](https://github.com/yeelp/Distinct-Damage-Descriptions/files/6710834/crash-2021-06-24_18.37.16-client.txt)
