### ISSUE TITLE
Multiple issues with shields

### ISSUE THREAD

**Issue by xijtsjis** [yeelp/Distinct-Damage-Descriptions#60]
Sorry if these should be separate issues, just felt spammy to do three at once.

1. **Shields do... nothing.**
   Tested with different damage distributions (including having all at 100%), against multiple mobs, and took full unreduced damage from everything while the shield was up. Happens even with just DDD so it's not a compatibility issue.

2. **Cannot apply shield effectiveness to weapons.**
   Relevant with [Sword Blocking Combat](https://www.curseforge.com/minecraft/mc-mods/golden-age-combat). I'm not certain this is actually what's happening considering the first point, but they don't display on the tooltip at all so I have to assume it's not being applied.

3. **Shield tooltip uses the wrong strings.**
   `.shielddist` and `.effectiveness` are swapped. 

   ![shield](https://user-images.githubusercontent.com/49894915/123918514-f1f6e500-d951-11eb-8c62-2fc007ce5fae.png)

edit: Feel like I should point out, armor is working perfectly fine. The problem is just for shields.

**Comment by yeelp** [comment]
Maybe something went wrong with the shields and I overlooked something, so I'll take a look there. The tooltips I definitely messed up, but that's a quick fix.

Shield Effectiveness is only applicable to shields. Sword blocking is a custom mod feature (well, it's an old feature brought back by mods, but it is a 'foreign concept' to vanilla 1.12.2) and after looking at the source for Golden Age Combat, it's not directly compatible with DDD. DDD sets damage sources to be unblockable so it can bypass vanilla armor deductions (Forge doesn't really offer a better way to handle this from my research. I could be wrong though, open to suggestions here). If the sword block events happen before DDD fires (and it probably doesn't as DDD wants to fire first), then things would work as expected, in the sense that the sword would reduce all types of damage. 

I may be able to tweak some of the logic here to better accommodate things like sword blocking, but I imagine there are many mods that bring back the old sword blocking feature and they all probably do it in different ways. If I want to support sword blocking, I have to add the support manually for the specific mod in question, which means I'm picking favorites on which sword blocking mod works with DDD and which one doesn't, and that's a slightly awkward position to be in.

A solution here is to bring back sword blocking as a feature in DDD itself and support it that way, then I have more control over how I can interact with it. But I'm on the fence about that.

Good to know that armor still works though haha

**Comment by xijtsjis** [comment]
That's a fair stance to take. From what I could find though, Golden Age Combat is the only mod on Curseforge that does sword blocking, at least for Forge. (There's a few for Fabric.) Even [Classic Combat](https://www.curseforge.com/minecraft/mc-mods/classic-combat) doesn't from a quick test, at least in 1.12. Considering that I think it'd be fine to implement support for it, but that's obviously your call.

**Comment by Xarmat-GitHub** [comment]
Test Version: DDD 1.3
- Have tried the shields too, but they don't block any damage at the moment, damage get 100% bypass through shields
- Try to change the values in the config (didn't help)
- Item Tooltip values works fine :+1:
- As mention above: Armor works fine, Weapons too, soon I will test the build in ddd_damage types (later the mobs)
- Hope this helps a bit

**Comment by yeelp** [comment]
The sword blocking being able to block distributions should be opened in a separate issue as a feature request to help track it independently of this one
