### ISSUE TITLE
DDDCombatRules.getLastHit(UUID) should return an Optional<HitInfo> to avoid NPE's or be changed altogether

### ISSUE THREAD

**Issue by yeelp** [yeelp/Distinct-Damage-Descriptions#62]
Mods like 12M (MmmMmmMmmMmm) fire their own LivingHurtEvent without a LivingAttackEvent. This reveals a fundamental problem:

If a LivingHurtEvent is fired without a LivingAttackEvent, the whole thing crashes.

Either wrap the HitInfo in an Optional, or redo the damage calculation process.

**Comment by Xarmat-GitHub** [comment]
Tentacle Pastbin:
https://pastebin.com/rLZgLt75
