### ISSUE TITLE
Sword Blocking Combat (= Golden Age Combat) integration

### ISSUE THREAD

**Issue by xijtsjis** [yeelp/Distinct-Damage-Descriptions#66]
[Golden Age Combat](https://www.curseforge.com/minecraft/mc-mods/golden-age-combat)

Broadly comes down to two things (afaict):
- Allow shield effectiveness to be applied to `ItemSword` when Sword Blocking Combat is installed
- Integrate DDD features into its blocking system.

**Comment by yeelp** [comment]
To me: Additional info about this was discussed in #60 if needed

**Comment by yeelp** [comment]
If Golden Age Compat allows swords to block similar to shields, then adding ItemSword to shieldClasses in the compat section of DDD's config in 1.7 should get this working. If it doesn't work, please reopen this issue.
