### ISSUE TITLE
Issue with customnpcs

### ISSUE THREAD

**Issue by viperc48** [yeelp/Distinct-Damage-Descriptions#67]
The dialogue command from customnpcs does not work when DDD is installed and debug.log shows an error.
[debug.log](https://github.com/yeelp/Distinct-Damage-Descriptions/files/7149109/debug.log)

**Comment by yeelp** [comment]
Seems to be that DDD can't find and attach mob resistances to the NPC, then tries to give a warning about it using the entity's name, which causes a problem with customnpcs because somehow the name doesn't exist or something

**Comment by viperc48** [comment]
So the dialog commands I was testing are /noppes dialog show <player> <dialog id> <name> and /noppes dialog read <player> <dialog id> <name> . The dialogues are drawn from the global pool of dialogues(not attached to any npc) and should show the dialogue in a menu. Normal npc dialog works fine as it is accessed by right-clicking a npc that has dialogue attached to it.

**Comment by yeelp** [comment]
Probably yes, but the better idea is to just check if the problem occurs and assign a default value instead of crashing, and throw a warning in the console.
