### ISSUE TITLE
All death messages are duplicated in chat

### ISSUE THREAD

**Issue by James103** [yeelp/Distinct-Damage-Descriptions#7]
As of Distinct Damage Descriptions 1.0.0-beta for MC 1.12.2, when you die, the death message appears twice in chat and 4 times in log (expected: once in chat and 2x in log unless you die twice to the same cause).

Example: When a player is crushed by a falling anvil, expected output:
> Player was crushed by a falling anvil

Actual output:
> Player was crushed by a falling anvil
> Player was crushed by a falling anvil

**Comment by yeelp** [comment]
Hmmm, this was my initial thought. Probably just a slight oversight.

**Comment by yeelp** [comment]
I believe commit 8e13ad07e21782c2fdcc41513776b85e354b01d2 actually resolves this. Adding 		

https://github.com/yeelp/Distinct-Damage-Descriptions/blob/8e13ad07e21782c2fdcc41513776b85e354b01d2/src/main/java/yeelp/distinctdamagedescriptions/handlers/DamageHandler.java#L53

Will prevent the messages from popping up when custom death messages are disabled. When custom death messages are enabled, a world restart is required and that sets the showDeathMessages gamerule to false.
