### ISSUE TITLE
[Suggestion] Resistance Reduction for Weapons

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#71]
Yeelp once told an example of "slime cubes" and "thunder" damage type.
`https://discord.com/channels/750481601107853373/763191962106069012/886944310937915403`

The Slime in this example has a "immunity" to "thunder". But when the "sound wave" is strong enough, then it will "bypass" the immunity.

At the moment, Sly Strike will ignore all immunities. And Brute Force reduce all resistances by 10% for each level.

I thought about a way to enable weapons build in "brute force" for there damage types.

Can be look like this:
```
S:"Weapon Base Damage">
minecraft:iron_shovel;[(b, 1)];[] -> early game weapon, no resistance reduction
spartanweaponry:mace_iron;[(b, 1)];[(b, 0.4)] -> mid game weapon with 40% bludgeoning resistance reduction
embers:grandhammer;[(b, 1)];[(b, 0.8)] -> late game weapon with 80% bludgeoning resistance reduction
one more:
minecraft:iron_axe;[(s, 0.6), (b, 0.4)];[(s, 0.2)] -> only 20% slashing reduction; 
>
```

Encounter Example:
- mowziesmobs:ferrous_wroughtnaut
![grafik](https://user-images.githubusercontent.com/69967920/135980257-0047edb8-f917-4567-a22e-5784767d3f02.png)

- Resistance: S = 140, B = 90, P = 200
- vs shovel: 90%- 0% -> 10% effective damage (no armor calculation)
- vs mace: 90%- 40% -> 50% effective damage (no armor calculation)
- vs grandhammer: 90%- 80% -> 90% effective damage (no armor calculation)

This would allow progression for early, mid and late game and will enable the balancing of mobs and bosses more easier.
This mechanic would also allow to "tier" spells:
- Ice Bolt (early)
- Ice Lance (mid)
- Ice Storm (late)

Fire Example:
- Iron Golem S = 100, B = 70, P = 120, **Fire = 100**
- Fire Ball -> 0% bypass (only surface, low impact) -> 0 % damage
- Fire Laser -> 40% bypass (smelt region of body) -> 40% damage
- Fire Inferno -> 80% bypass (high temperature, smelt body strong) -> 80% damage

On top of this, "brute force" enchantment will work too.

Optional: Same solution for "immunities"
`embers:grandhammer;[(b, 1)];[(b, 0.8)];[(b)] -> late game weapon with 80% bludgeoning resistance reduction + bypass bludgeoning resistance`

I know about the work this will cause (sorry Yeelp, but your mod still awesome without this too), but this may be a nice way to open progression bind to items and a motivation to craft next tier items (instead of using tinkers weapons with 10 damage modifiers and upgrades).

Thanks for your patient and have a blessed day.

_Integration Needed: Tinker Based Mods_

**Comment by Xarmat-GitHub** [comment]
Interesting... I currently working on mob resistance in my mobpack.
And I start to compare mobs with each other in my mind background and type wrong values in my sheet.

So I started with insect  like creatures and ten set:
- Spider 0s,0p,0b (because I want them get full damage from all weapons)
- Fire_Beetle 0.2s, 0p, 0b (because the insect armor  will be stronger then the spider one.... I thought :flushed:)

**Here is a big balancing challenge.**
Set-Up values instinctive will NOT work... :/
I have to reset my mind at each mob and question myself how I will use this mob and where. Then I can set right values for it.

So having let say different kinds of "blades" will make bypassing resistance "intuitive".
- Knife vs cave spiders (10% reduction) (thin shell)
- Sword vs large spiders (30% reduction) (a bit more force needed)
- Greatsword vs bis bugs (50% reduction) (a lot more force needed to get through the shell)

OR using other types of weapons to "smash" them to death. :thinking: 

This is a huge thing for intuitive playing.
When the player moves in the game world, and has an encounter, then he must be able to swap to the best weapon based by instinct.
Boss fights and other encounters may need more preparation (and this gives the game more depth and is good) .

When around and fight against animal type of monsters, then I switch instantly to my fire blade (fire + slash).
When I get attacked by a stone golem then I take my maze to smash him in pieces (b).
When I forget my maze in the base, then I will not use my knife... I will take my greatsword to cut / smash the golem in pices (not as effective like a mace or hammer, but good enough).

All of those are indistinctly correct and give more depth while fighting.
No player will take a knife with poison and attack a mechanical iron golem with it.
So they use an lighting infused hammer and go party. 🥳 

Lol, my head get hot from this stuff. 😅

**Comment by yeelp** [comment]
An interesting idea, but such an addition would involve a massive overhaul to core DDD mechanics *and* config, as you're already aware of. The main thing I want to avoid here is changing how existing config values are entered again.

However, if I want to add this, I'd only do it for resistances, not immunities. Maybe. Even thinking about it now, I'm not sure how I'd want to approach this should I choose to add it. For now, Sly Strike and Brute Force are good enough implementations of this kind of system.

That being said, DDD 1.4 will introduce new CraftTweaker events you can hook into that would allow you to ignore/grant immunities, among a few other things. It could allow you to bypass immunities for players using certain items.
