### ISSUE TITLE
[Suggestion] Config: Min Damage Bypass

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#72]
When the player stuck in an encounter with the wrong weapon, it can be that the mob never get any damage from player attacks and he have to die or run away.

Here is a possible solution: When the damage will be reduced beyond 10%, then it will all ways inflict 10% weapon damage.
This enable the player the chance to survive and still makes the encounter really hard.

(At the moment, the modpack makers have to be precise while setting the values. This option will make "lazy" solutions less painfull)

`X:"Bypass damage reduction" = 0%`

This ticket can be closed if this not fit the vision of the mod (lol... all tickets can be closed any time, so no "bossy" talk here). 😉

**Comment by yeelp** [comment]
> it can be that the mob never get any damage from player attacks and he have to die or run away.

In essence, that's the point. DDD encourages players to prepare for encounters beforehand and to not just brute force everything (unless they have that specific enchantment lol). If they walk into an encounter unprepared and find themselves unable to damage the mob, well then they walked into the encounter unprepared. That's the consequence.

However, I already added this to the milestone, so I must've had something in mind, not sure I remember exactly what that was. I can see the point of making the punishment less harsh in some situations.

**Comment by Xarmat-GitHub** [comment]
This would allow the modpack makers to decide if there modpack is punishing really hard (0% bypass) or to allow wrong decisions to be less painful.

In theory:
- Having the right weapon will lead to 3 blow to kill
- Having a totally wrong weapon (with 10% bypass) will lead to 30 blows to kill -> more time effort -> durability cost

The player has also some time (~45 seconds) why his weapon is the wrong one. : D

**But something that may be think about:**
The "shield" effects should stay the same. That mean, that attacking a mob, will cause the same amount of shield particle effects as it would be with 0% bypass.
