### ISSUE TITLE
[Suggestion] Config: Use Mod IDs to enable Armor Functionality

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#76]
Option to enter a mod name into DDD to allow full functionality without any configuration.

Example:
S:"Armor Resistance" <
modid:ignor>
S:"Shield Effectiveness" <
modid:ignor>

Result: All Armor from this Mod and all Shields will get 100% S,P,B Values.
All other damage types will do 100% damage.

This is an element to think about, but it is not necessary, modpack makers know what they have to do when adding DDD in there modpack.

**Comment by yeelp** [comment]
With #102, this is likely no longer needed
