### ISSUE TITLE
Compatible with MineFantasyReforged

### ISSUE THREAD

**Issue by MokoBlack** [yeelp/Distinct-Damage-Descriptions#78]
This mod also have a damage type system similar to your mod.
I don't know if this mod can work well with it.

**Comment by yeelp** [comment]
I haven't heard of the mod before. I checked it out on CurseForge, but there doesn't seem to be much of an explanation about a damage type system that's similar to this mod. Can you elaborate a little bit on it?

**Comment by ainlzj** [comment]
> 我以前没有听说过这个mod。我在CurseForge上检查了一下，但似乎没有多少关于类似于这个mod的伤害类型系统的解释。你能详细说说吗？

https://www.curseforge.com/minecraft/mc-mods/minefantasy-reforged

**Comment by yeelp** [comment]
This issue is being closed as there is no issue with the two mods as far as I am aware.
