### ISSUE TITLE
Lycanitemobs compatibility issue

### ISSUE THREAD

**Issue by asketmc** [yeelp/Distinct-Damage-Descriptions#86]
Forge server stops at initialising DDD mod stage in case Lycanitemobs are present.

Confirmed on Lycanites versions: 2.0.7.2 and 2.0.8.5
DDD version: 1.4.2

**Steps to reproduce:**
1) Set up a forge server with DDD and Lycanitemobs mods
2) Launch server

**Expected result:**
Server starts up

**Actual results:**
Server crashes on mod init stage

_Crash logs attached:_
https://pastebin.com/7Z1JLp2C

**Comment by James103** [comment]
Converted paste to file as the paste was uploaded to Pastebin with an expiration date: [crash.txt](https://github.com/yeelp/Distinct-Damage-Descriptions/files/9930473/crash.txt)

**Comment by yeelp** [comment]
Simple side error. Client stuff being done server side. Should be a simple fix, which I will include in the next update when I get the time to work on it. Thank you!
