### ISSUE TITLE
[Suggestion] NBT：Location of NBT

### ISSUE THREAD

**Issue by undyingtheglass** [yeelp/Distinct-Damage-Descriptions#87]
yeelp,I think DDD mod is fabulous, but I found a problem with DDDMOD (I'm not sure if it's intentional or not configured): NBT is not displayed in the correct position, and in general, NBT data for an item will be displayed inside the main compound:tag
![11 (2)](https://user-images.githubusercontent.com/99233721/201469718-19b9c456-bdb4-4a94-b2e6-78306195b8bd.png)
(It's the part framed by the red thread)
But the NBT data stored by this mod is here
![KJDCM51NJ3)22NCH7A4WH42](https://user-images.githubusercontent.com/99233721/201469856-fed7602a-d81b-4049-9c19-05eaa061a529.png)
So, this leads to a problem: I can't set the damage type via NBT, which is fatal for some mods (mods like slashblade that rely on NBT to distinguish between different items) I hope you can put the NBT of this mod into the main compound, which makes this mod more customizable

Finally, thank you for making us use such a fun mod, I believe that with our joint efforts, this mod will definitely get better
PS:My English is poor, so there may be some when reading... Strange or impolite, please don't care, if there is something unclear, please let me know, I will explain

**Comment by yeelp** [comment]
Thanks for the suggestion! However, I do not manually serialize NBT data. DDD's information is stored as a Forge Capability, and Forge's Capability system works wonders. This is just how Forge stores capabilities; as it's own NBT compound tag. I believe this is for a specific reason, though not sure exactly why.

Could you explain why this causes a problem? Specifically, when you mentioned:

> (mods like slashblade that rely on NBT to distinguish between different items)

Why is the fact that Slashblade relies on NBT to distinguish between different items problematic? Could you provide a description of what it is you are trying to do, what you believe the intended behavior is, and what happens instead? There may be other options to resolve the issue.

**Comment by undyingtheglass** [comment]
I'm sorry I just saw your question now,So let me describe the problem I encountered.
Let me give you an example, in the slashblade mod, some items share an item ID, like this:
![Uploading QQ
![QQ截图20221126180527](https://user-images.githubusercontent.com/99233721/204083364-390506e7-a08a-47a9-a940-ad99c7c8892e.png)
截图20221126180431.png…]()
![QQ截图20221126180554](https://user-images.githubusercontent.com/99233721/204083368-2d82ba02-7eb3-487c-93b3-ba20cf70b0c8.png)

**Comment by undyingtheglass** [comment]
I'm sorry, my previous description doesn't seem clear and concise, 
I hope this mod can edit damage types for different items of the same item id through NBT, and can modify this NBT with CraftTweaker,
 but this mod currently places NBT outside the main directory, which makes me unable to modify it through CraftTweaker, if I modify NBT directly, It will cause all the damage types of unconfigured items to become the damage type I modified,
finally, wish your mod to get better！

**Comment by yeelp** [comment]
Ah I see. I have a slightly better configuration system planned in #82 which would allow for stuff like this. Currently on my todo list.
