### ISSUE TITLE
Crash on startup (maybe tinker integration)

### ISSUE THREAD

**Issue by Biviho** [yeelp/Distinct-Damage-Descriptions#88]
hi! i'm having a crash on startup, by reading it it looks like it has something to do with the tinker integration, it might be because i have disabled all the tinker weapons to keep only the smelter

https://pastebin.com/6R5suGNe

**Comment by yeelp** [comment]
Pretty much right on the money. To be specific, it's only the *projectiles* that cause the crash, as DDD registers them with projectile distributions specifically so toolkits work correctly. Didn't occur to me at the time that they may be disabled.
