### ISSUE TITLE
[Bug] - Weird lines in configs

### ISSUE THREAD

**Issue by SSKirillSS** [yeelp/Distinct-Damage-Descriptions#9]
example_creature_type.json
![image](https://user-images.githubusercontent.com/38190325/90961997-6866c300-e4b5-11ea-8080-3c99a5445f7d.png)
![image](https://user-images.githubusercontent.com/38190325/90962015-79afcf80-e4b5-11ea-89eb-8972970596ac.png)

example_damage_type.json
![image](https://user-images.githubusercontent.com/38190325/90962022-86342800-e4b5-11ea-8375-0e0dad2c4940.png)
![image](https://user-images.githubusercontent.com/38190325/90962025-8a604580-e4b5-11ea-9714-1ad8bb836207.png)

distinctdamagedescriptions-1.0.0-beta

**Comment by yeelp** [comment]
There definitely seems to be something going wrong with how it's generating the config files, as the sources it uses [here](https://github.com/yeelp/Distinct-Damage-Descriptions/tree/master/src/main/resources/example) don't have these problems, and this never happened to me locally.

I'm not entirely sure this will be relevant, but what OS do you run? This mod was developed and tested on a Windows machine, and I tried to make sure to accommodate Mac OS, but I may have failed on that front.

If you are running Windows as well, then I'm really not sure how that happened. If you delete and regenerate the files, does it still happen?

**Comment by SSKirillSS** [comment]
Win10 LTSC 1809 x64

Regenerating files does nothing. Issue still appears.

**Comment by yeelp** [comment]
Hmmm... This may take some time to figure out then. I'll see what I can come up with
